<?php

use \Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use \App\Models\Country;
class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['name' => 'Afghanistan'],
            ['name' => 'Albania'],
            ['name' => 'Algeria'],
            ['name' => 'Argentina'],
            ['name' => 'Australia'],
            ['name' => 'Austria'],
            ['name' => 'Bahrain'],
            ['name' => 'Belarus'],
            ['name' => 'Bangladesh'],
            ['name' => 'Belgium'],
            ['name' => 'Belize'],
            ['name' => 'Bermuda'],
            ['name' => 'Bhutan'],
            ['name' => 'Brazil'],
            ['name' => 'Cambodia'],
            ['name' => 'Cameroon'],
            ['name' => 'Canada'],
            ['name' => 'Chile'],
            ['name' => 'China'],
            ['name' => 'Colombia'],
            ['name' => 'Comoros'],
            ['name' => 'Congo'],
            ['name' => 'Costa Rica'],
            ['name' => 'Cuba'],
            ['name' => 'Cyprus'],
            ['name' => 'Denmark'],
            ['name' => 'Ecuador'],
            ['name' => 'Egypt'],
            ['name' => 'Fiji'],
            ['name' => 'Finland'],
            ['name' => 'France'],
            ['name' => 'Germany'],
            ['name' => 'Ghana'],
            ['name' => 'Greece'],
            ['name' => 'Haiti'],
            ['name' => 'Honduras'],
            ['name' => 'Hong Kong'],
            ['name' => 'Hungary'],
            ['name' => 'Iceland'],
            ['name' => 'India'],
            ['name' => 'Indonesia'],
            ['name' => 'Iran'],
            ['name' => 'Iraq'],
            ['name' => 'Ireland'],
            ['name' => 'Israel'],
            ['name' => 'Italy'],
            ['name' => 'Jamaica'],
            ['name' => 'Japan'],
            ['name' => 'Jordan'],
            ['name' => 'Kazakhstan'],
            ['name' => 'Kenya'],
            ['name' => 'Korea (North)'],
            ['name' => 'Korea (South)'],
            ['name' => 'Kuwait'],
            ['name' => 'Kyrgyzstan'],
            ['name' => 'Laos'],
            ['name' => 'Lebanon'],
            ['name' => 'Liberia'],
            ['name' => 'Libya'],
            ['name' => 'Luxembourg'],
            ['name' => 'Malaysia'],
            ['name' => 'Maldives'],
            ['name' => 'Mali'],
            ['name' => 'Mexico'],
            ['name' => 'Moldova'],
            ['name' => 'Monaco'],
            ['name' => 'Mongolia'],
            ['name' => 'Myanmar'],
            ['name' => 'Namibia'],
            ['name' => 'Nepal'],
            ['name' => 'Netherlands  '],
            ['name' => 'New Zealand'],
            ['name' => 'Nigeria  '],
            ['name' => 'Norway'],
            ['name' => 'Oman'],
            ['name' => 'Pakistan'],
            ['name' => 'Palestinian'],
            ['name' => 'Panama'],
            ['name' => 'Papua New Guinea'],
            ['name' => 'Paraguay'],
            ['name' => 'Peru'],
            ['name' => 'Philippines'],
            ['name' => 'Poland'],
            ['name' => 'Portugal'],
            ['name' => 'Qatar'],
            ['name' => 'Romania'],
            ['name' => 'Russian Federation'],
            ['name' => 'Rwanda'],
            ['name' => 'Saudi Arabia'],
            ['name' => 'Serbia'],
            ['name' => 'Singapore'],
            ['name' => 'Somalia'],
            ['name' => 'South Africa'],
            ['name' => 'Spain'],
            ['name' => 'Sri Lanka'],
            ['name' => 'Sudan'],
            ['name' => 'Swaziland'],
            ['name' => 'Sweden'],
            ['name' => 'Switzerland'],
            ['name' => 'Syria'],
            ['name' => 'Taiwan'],
            ['name' => 'Tajikistan'],
            ['name' => 'Tanzania'],
            ['name' => 'Thailand'],
            ['name' => 'Togo'],
            ['name' => 'Tunisia'],
            ['name' => 'Turkey'],
            ['name' => 'Turkmenistan'],
            ['name' => 'Uganda'],
            ['name' => 'Ukraine'],
            ['name' => 'United Arab Emirates'],
            ['name' => 'United Kingdom (UK)'],
            ['name' => 'United States of America (USA)'],
            ['name' => 'Uruguay'],
            ['name' => 'Uzbekistan'],
            ['name' => 'Vanuatu'],
            ['name' => 'Venezuela'],
            ['name' => 'Viet Nam'],
            ['name' => 'Yemen'],
            ['name' => 'Zambia'],
            ['name' => 'Zimbabwe']
        ]);

    }
}
